# This workflow will run tests using node when changes are pushed
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Jest Test

on:
  pull_request:
    branches: main

jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm install
      - run: npm test
